[package]
name = "pacw"
version = "0.2.5"
edition = "2018"

[profile.release]
lto = "fat"
codegen-units = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = {version = "0.8.2", features = ["serde", "v4"]}
